language: node_js
node_js:
  - 0.8
  - '0.10'
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install inkscape
before_script:
  - npm install -g grunt-cli
  - npm install
  - npm link
after_success:
  - grunt clean
  - npm run coveralls
